spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: katya
  sql:
    init:
      mode: always
  docker:
    compose:
      enabled: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: DEBUG